# Copyright (C) 2019 Nomango

---

app:
  name: Bellex
  address: 0.0.0.0
  port: 8080
  debug: false
  session:
    name: bellex_session
    provider: file
    providerConfig: ./session

database:
  user: bellex
  password: Bellex2019
  uri: tcp(127.0.0.1:3306)/bellex?charset=utf8&loc=Local

tcp:
  port: 7777
