# Copyright (C) 2019 Nomango

---

app:
  name: Bellex
  address: localhost
  port: 8080
  debug: true
  session:
    name: bellex_session
    provider: memory
    providerConfig: 

database:
  user: root
  password: 
  uri: tcp(127.0.0.1:3306)/bellex?charset=utf8&loc=Local

tcp:
  port: 7777

rpc:
  port: 7778
